### ISSUE TITLE
StopToken serialization issue

### ISSUE THREAD

**Issue by stockaiz** [tjardoo/openai-client#9]
Greetings
When `ChatCompletionParameters` is serialized and `stop` is Some, it's serialized in `"stop":{"String":"stop_text"}` which causes an issue with the OpenAI APIs: `EndpointError("{\n  \"error\": {\n    \"message\": \"{'String': '{thoughts'} is not valid under any of the given schemas - 'stop'\",\n    \"type\": \"invalid_request_error\",\n    \"param\": null,\n    \"code\": null\n  }\n}\n")`

I think the issue is with how the `StopToken` enum is serialized.

**Comment by tjardoo** [comment]
Thanks for reporting! I've just fixed this issue with this [commit](https://github.com/tjardoo/openai-client/commit/9b5a018bd349b9d622d2fd5ac8b97ee09f88bafc) in `0.2.9`. It was indeed the way the `StopToken` was serialized - fixed with [Serde Untagged](https://serde.rs/enum-representations.html#untagged).

```rust
// example 1
stop: Some(StopToken::String("\n".to_string())),

// example 2
stop: Some(StopToken::Array(vec![
    "\n".to_string(),
])),
```
